<a href="https://colab.research.google.com/github/heemin2230/DeepLearning/blob/master/6%EC%9E%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AND 게이트


In [ ]:
import numpy as np

def AND(x1,x2,w1=0.5,w2=0.5,b=-0.7):
  x = np.array([x1,x2])
  w = np.array([w1,w2])
  y = np.sum(x*w) + b

  if y>=0:
    return 1
  elif y<0:
    return 0

In [ ]:
print("AND(0,0) = ",AND(0,0))
print("AND(0,1) = ",AND(0,1))
print("AND(1,0) = ",AND(1,0))
print("AND(1,1) = ",AND(1,1))

AND(0,0) =  0
AND(0,1) =  0
AND(1,0) =  0
AND(1,1) =  1


# NAND 게이트


In [ ]:
import numpy as np

def NAND(x1,x2,w1=-0.5,w2=-0.5,b=0.7):
  x = np.array([x1,x2])
  w = np.array([w1,w2])
  y = np.sum(x*w) + b

  if y>=0:
    return 1
  elif y<0:
    return 0

In [ ]:
print("NAND(0,0) = ",NAND(0,0))
print("NAND(0,1) = ",NAND(0,1))
print("NAND(1,0) = ",NAND(1,0))
print("NAND(1,1) = ",NAND(1,1))

NAND(0,0) =  1
NAND(0,1) =  1
NAND(1,0) =  1
NAND(1,1) =  0


# OR 게이트

In [ ]:
import numpy as np

def OR(x1,x2,w1=0.5,w2=0.5,b=-0.2):
  x = np.array([x1,x2])
  w = np.array([w1,w2])
  y = np.sum(x*w) + b

  if y<=0:
    return 0
  elif y>0:
    return 1

In [ ]:
print("OR(0,0) = ",OR(0,0))
print("OR(0,1) = ",OR(0,1))
print("OR(1,0) = ",OR(1,0))
print("OR(1,1) = ",OR(1,1))

OR(0,0) =  0
OR(0,1) =  1
OR(1,0) =  1
OR(1,1) =  1


# XOR 게이트

In [ ]:
def XOR(x1,x2):
  s1 = OR(x1,x2)
  s2 = NAND(x1,x2)
  y = AND(s1,s2)
  return y

In [ ]:
print('XOR(0,0) = ',XOR(0,0))
print('XOR(0,1) = ',XOR(0,1))
print('XOR(1,0) = ',XOR(1,0))
print('XOR(1,1) = ',XOR(1,1))

XOR(0,0) =  0
XOR(0,1) =  1
XOR(1,0) =  1
XOR(1,1) =  0


# 다차원배열

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
np.ndim(a)

1

In [ ]:
a.shape

(4,)

In [ ]:
a.shape[0]

4

In [ ]:
b = np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
np.ndim(b)

2

In [ ]:
b.shape

(3, 2)

# 행렬의 내적


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
a.shape

b = np.array([[5,6],[7,8]])
b.shape

np.dot(a,b)

array([[19, 22],
       [43, 50]])

# n차 행렬이 아닌 행렬 (A,B)·(B,C) = (A,C)

In [ ]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
a.shape

b = np.array([[7,8,9,10],[11,12,13,14]])
b.shape

np.dot(a,b)

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

# 신경망의 내적

In [ ]:
X = np.array([1,2])
X.shape


(2,)

In [ ]:
W = np.array([[1,3,5],[2,4,6]])
print(W)


[[1 3 5]
 [2 4 6]]


In [ ]:
W.shape


(2, 3)

In [ ]:
Y = np.dot(X,W)
print(Y)

[ 5 11 17]
